### ISSUE TITLE
Campaign encounter creation

### ISSUE THREAD

**Issue by sethtrain** [sethtrain/marvin#19]
Associate an encounter with a campaign

**Comment by omnomicon** [comment]
i think i have a pretty good idea of what a campaign is, how are we defining an encounter? I'd tend toward a relationship like campaign HAS-A session HAS-A encounter?

**Comment by sethtrain** [comment]
It would be A Campagin (game) HAS-MANY encounters.  Those encounters may or may not be "encountered" during a session depending on the character actions and directions

**Comment by omnomicon** [comment]
oh i see. i was coming at it from a player's POV. that makes sense form the DM's perspective though
