### ISSUE TITLE
Narrative

### ISSUE THREAD

**Issue by sethtrain** [sethtrain/marvin#22]
From a DM standpoint it would be nice to manage the game narrative.  My mind waivers back and forth from simple to complex.

#### Simple

Can be as simple as "Chapter" title and narrative.

#### Complex

Might be cool to have "Chapter" title and narrative with the potential to "branch" in the narrative based on PC actions.  My initial thought is that it could build some form of a decision tree associating "encounters" with the narrative.

Maybe the decision tree idea is too complex which means we might be able to just "link" encounters from within the text taking us back to simple with the ability to handle "special" encounter links.

Thoughts?

**Comment by sethtrain** [comment]
I'm leaning towards punting on complexity and going with "Simple with encounter linking"

**Comment by sethtrain** [comment]
I also like the idea of "links" within these types of things that might trigger events for PC users (i.e. Sounds, Images or map transitions/actions) which would be useful for sethtrain/marvin#19

**Comment by sethtrain** [comment]
Another cool thing would be for the DM to have the ability to call for a roll (with certain modifiers) from the PCs.   So at any point the DM clicks the certain link and it drops an action into the PC view which when clicked would trigger /roll (and maybe one day gathering the results back in Narrative view for handouts or additional narrative bonuses)

**Comment by omnomicon** [comment]
Definitely prefer the simple option to the complex one. I think the complex one takes this into the realm of a video game and not tools to manage a table-top campaign. It could even be something as simple as DM "notes" where notes have a title & body. Could even be expanded to notes/journal entries for players too. Or even in-game notes, like a letter found on a bookshelf.

**Comment by sethtrain** [comment]
Right, if we have the ability to do Markdown plus linking something as simple as notes would be good enough, might be work having the ability to "jump to" headings in the notes but should be fine.

**Comment by omnomicon** [comment]
There's also a danger here of re-implementing a wiki or, worse: wordpress :)

**Comment by sethtrain** [comment]
:truestory:

**Comment by omnomicon** [comment]
We should probably come up with a rubric for deciding what fits in marvin and what doesn't. I'll start another ticket.

**Comment by sethtrain** [comment]
OK, sounds good.

**Comment by omnomicon** [comment]
https://github.com/sethtrain/marvin/issues/27

**Comment by sethtrain** [comment]
So I am going to official propose...

Narrative Notes:

- TItle
- Body (formatted with Markdown)

If we want to extend it in any way we can do that with front-end "tricks":

Chapter 1
========

This is the narrative behind chapter one.

>  Here is a quote which means you actually say this to the players.

`[E: "Encounter 3"]` (or some derivative) would be interpreted on the front-end and "linked" to trigger an action that displays "Encounter 3 narrative".

**Comment by sethtrain** [comment]
I only wonder if we should split it up or just have one notebook per game.

**Comment by sethtrain** [comment]
I'm also now wondering if we should include a type (Story, Encounter) and keep the Narrative in one table.  Thoughts?

**Comment by omnomicon** [comment]
I like 
```json
{
  "title": "Chapter 1",
  "body": "markdown\nwith **stuff**"
}
```

`type` always strikes me as a smell. it normally means you're trying to express something that your model can't. I wonder if we could use the counter system to tag a note? i mean it's an object like anything else. "story" or "encounter" are just tags.

So maybe: `/counter "Chapter One" "enounter" 0` (the number would be meaningless...probably...up to the DM though). Also, tags can overlap, so you could also apply `/counter "Chapter One" "social" 0 `
