### ISSUE TITLE
Should we include immutable.js?

### ISSUE THREAD

**Issue by sethtrain** [sethtrain/marvin#29]
https://facebook.github.io/immutable-js/

Not much going on at the moment but would it be beneficial to have this constraint at the moment?

**Comment by omnomicon** [comment]
Works for me. Serverless can even let you include dependencies per-function, so we don't have to include it as a global dependency. `close-game` includes `slug`, for instance, because I didn't want to write a slugifier :)

**Comment by sethtrain** [comment]
That's a really nice feature.
